In [49]:
import torch

torch.Tensor([[1, 2, 3], [4, 5, 6]])

In [50]:
x = torch.randn(2, requires_grad=True) #parameter 1
k = torch.Tensor([2,4]) #input data
b = torch.Tensor([5]) #parameter 2
y = k*x+b #linear model

In [51]:
k, b

(tensor([2., 4.]), tensor([5.]))

In [52]:
y

tensor([ 6.8203, -4.2260], grad_fn=<AddBackward0>)

In [53]:
 # y_known = torch.Tensor([5,9])
y_known = torch.Tensor([2,4])
loss = (torch.sum(y_known - y))**2 #loss function
loss

tensor(11.5988, grad_fn=<PowBackward0>)

In [54]:
loss.backward() #calculate gradients
m.grad

tensor([ -72.0741, -144.1481])