Introduction

# 1. PyTorch Basics

## Import

In [1]:
import random
import numpy as np
import torch

seed=1234
random.seed(seed)
np.random.seed(seed)
torch.random.manual_seed(seed)
if torch.cuda.is_available():
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

## Numpy & PyTorch
The syntax and usage of Numpy and PyTorch are very similar. <br>
Various operations are compatible. <br><br>

Here, we will learn basic attributes and operations.

In [2]:
m = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(m.ndim)   # rank
print(m.shape)  # shape

2
(3, 3)


In [3]:
m_torch = torch.FloatTensor(m)
print(m_torch.dim())    # rank
print(m_torch.shape)    # shape
print(m_torch.size())   # shape

2
torch.Size([3, 3])
torch.Size([3, 3])


In [4]:
print(m_torch)
print(m_torch[0])       # first row
print(m_torch[:, 0])    # first column
print(m_torch[1, 2])    # second row, third column

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([0., 1., 2.])
tensor([0., 3., 6.])
tensor(5.)


## Useful Operations

## Sum & Mean

In [5]:
m1 = torch.FloatTensor([np.arange(5)] * 5)
print(f'm1:\n {m1}')

print('------ SUM ------')
print(f'Sum all elements: {m1.sum()}')
print(f'Sum along axis 0: \n{m1.sum(dim=0)}')
print(f'Sum along axis 1: \n{m1.sum(dim=1)}')
print()

print('------ MEAN ------')
print(f'Mean all elements: {m1.mean()}')
print(f'Mean along axis 0: \n{m1.mean(dim=0)}')
print(f'Mean along axis 1: \n{m1.mean(dim=1)}')

m1:
 tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])
------ SUM ------
Sum all elements: 50.0
Sum along axis 0: 
tensor([ 0.,  5., 10., 15., 20.])
Sum along axis 1: 
tensor([10., 10., 10., 10., 10.])

------ MEAN ------
Mean all elements: 2.0
Mean along axis 0: 
tensor([0., 1., 2., 3., 4.])
Mean along axis 1: 
tensor([2., 2., 2., 2., 2.])


## Max & Argmax

In [6]:
m = torch.FloatTensor([[2, 1, 3], [-4, -5, 6]])
print(f'm:\n {m}')
print(f'max among all elements: {m.max()}\n')

print(f'max along axis 0: {m.max(dim=0)[0]}')
print(f'Argmax along axis 0: {m.max(dim=0)[1]}')
print(f'Argmax along axis 0 using argmax: {m.argmax(dim=0)}\n')

print(f'max along axis 1: {m.max(dim=1)[0]}')
print(f'Argmax along axis 1: {m.max(dim=1)[1]}')
print(f'Argmax along axis 1 using argmax: {m.argmax(dim=1)}')

m:
 tensor([[ 2.,  1.,  3.],
        [-4., -5.,  6.]])
max among all elements: 6.0

max along axis 0: tensor([2., 1., 6.])
Argmax along axis 0: tensor([0, 0, 1])
Argmax along axis 0 using argmax: tensor([0, 0, 1])

max along axis 1: tensor([3., 6.])
Argmax along axis 1: tensor([2, 2])
Argmax along axis 1 using argmax: tensor([2, 2])


## Squeeze & Unsqueeze

In [7]:
st = torch.FloatTensor([[-1, 0, 1], [3, 2, 1]])
print(f'tensor:\n {st}')
print(f'shape: {st.shape}\n')

st_unsqueeze = st.unsqueeze(1)
print(f'unsqueeze:\n {st_unsqueeze}')
print(f'shape: {st_unsqueeze.shape}\n')

st_squeeze = st_unsqueeze.squeeze(1)
print(f'squeeze:\n {st_squeeze}')
print(f'shape: {st_squeeze.shape}')

tensor:
 tensor([[-1.,  0.,  1.],
        [ 3.,  2.,  1.]])
shape: torch.Size([2, 3])

unsqueeze:
 tensor([[[-1.,  0.,  1.]],

        [[ 3.,  2.,  1.]]])
shape: torch.Size([2, 1, 3])

squeeze:
 tensor([[-1.,  0.,  1.],
        [ 3.,  2.,  1.]])
shape: torch.Size([2, 3])


## Concatenate

In [8]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0)) # axis 0
print(torch.cat([x, y], dim=1)) # axis 1

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Ones, Zeros, Full

In [9]:
ones = torch.ones(1, 2)
zeros = torch.zeros(3, 3)
full = torch.full((2, 2), -1)

print(f'ones: {ones}')
print(f'zeros: {zeros}')
print(f'full: {full}\n')

print(f'ones: {torch.ones_like(zeros)}')
print(f'zeros: {torch.zeros_like(full)}')
print(f'full: {torch.full_like(ones, 10)}')

ones: tensor([[1., 1.]])
zeros: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
full: tensor([[-1, -1],
        [-1, -1]])

ones: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
zeros: tensor([[0, 0],
        [0, 0]])
full: tensor([[10., 10.]])


## Mul & Matmul

In [10]:
t_1 = torch.FloatTensor([[1, 2], [3, 4]])
t_2 = torch.FloatTensor([[10], [20]])
print(f't_1 shape: {t_1.shape}')
print(f't_2 shape: {t_2.shape}\n')

# X 10 on the first row, X 20 on the second row
# Mul dis different from Matrix multiplication
# Column (second dimension) t_2 is broadcasted.
mul = torch.mul(t_1, t_2)
print(f'Mul:\n {mul}')
print(f'Mul shape: {mul.shape}')

# (2, 2) x (2, 1) = (2, 1) matrix
matmul = torch.matmul(t_1, t_2)
print(f'Matmul:\n {matmul}')
print(f'Matmul shape: {matmul.shape}')

t_1 shape: torch.Size([2, 2])
t_2 shape: torch.Size([2, 1])

Mul:
 tensor([[10., 20.],
        [60., 80.]])
Mul shape: torch.Size([2, 2])
Matmul:
 tensor([[ 50.],
        [110.]])
Matmul shape: torch.Size([2, 1])
