# 2. Useful Modules in PyTorch

## Modules in PyTorch
PyTorch provides frequently-used modules (or layers), such as FC and conv, for you to use off the shelf. <br>
Common ways to use is as follows: <br>
- Build module with configurations <br>
- Call module with input, like a function. <br>

In this tutorial, we will cover FC, convolution, maxpool, and activation functions.


## Import

In [ ]:
import numpy as np
import torch
import torch.nn as nn

np.random.seed(1234)
torch.manual_seed(1234)

# Fully-connected layer
- PyTorch provides fully-connected layer called ```nn.Linear```, which we looked at Assignment 3 and 4.
- As we did, it takes ```in_features``` and ```out_features``` as arguments.
- You can also speficy whether bias is used or not, using ```bias```. (Default is ```True```)
- Input and output shape is as follows:
    - Input: (# data, in_features)
    - Output: (# data, out_features)
- Refer to official document of [nn.Linear](https://pytorch.org/docs/master/generated/torch.nn.Linear.html) for more information.

In [ ]:
tensor = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'tensor shape: {tensor.shape}')

_, in_features = tensor.shape
out_features = 10

# Define layer (module)
fc_layer = nn.Linear(in_features=in_features, out_features=out_features, bias=True)

# Pass input
fc_layer_out = fc_layer(tensor)
print(f'fc layer output: \n {fc_layer_out}')
print(f'fc layer output shape: {fc_layer_out.shape}')

tensor shape: torch.Size([3, 3])
fc layer output: 
 tensor([[-1.4104, -0.6703,  0.3450,  0.4731,  0.3222,  0.4481,  0.9799, -0.4291,
          1.4523, -1.0640],
        [-4.2138, -1.9673, -0.7159,  1.0905,  1.6210,  0.8712,  1.2267, -1.5083,
          3.7323, -1.3673],
        [-7.0173, -3.2643, -1.7768,  1.7079,  2.9198,  1.2942,  1.4736, -2.5876,
          6.0123, -1.6707]], grad_fn=<AddmmBackward>)
fc layer output shape: torch.Size([3, 10])


In [ ]:
fc_weights = fc_layer.weight.data
fc_bias = fc_layer.bias.data

print(f'fc layer weights shape: \n{fc_weights.shape}')  # out_features x in_features
print(f'fc layer bias shape: \n{fc_bias.shape}')        # out_features

fc layer weights shape: 
torch.Size([10, 3])
fc layer bias shape: 
torch.Size([10])


## Convolution Layer
- PyTorch provides convolution layer called ```nn.Conv2d```, which we looked at Assignment 4.
    - There are different kinds of convolution, but we cover ```nn.Conv2d``` only.
- It takes ```in_channels```, ```out_channels```, ```kernel_size```, ```stride```, ```padding```, as basic arguments. (There are more, but we do not consider here.)
- ```kernel_size``` can be integer or a tuple.
    - If an integer is given, kernel is squared shape.
    - If a tuple is given, kernel is of the given shape.
    - Square kernel is common.
- Input and output shape is as follows:
    - Input: (# data, in_channel, in_height, in_width)
    - Input: (# data, out_channel, out_height, out_width)
- Refer to official document of [nn.Conv2d](https://pytorch.org/docs/master/generated/torch.nn.Conv2d.html) for more information.

In [ ]:
num_data = 3
in_channels = 1
input_height = 5
input_width = 5

conv_input = torch.rand(num_data, in_channels, input_height, input_width)

In [ ]:
out_channels = 3
kernel_size = 3
stride = 1
padding = 1

# (3, 3) squared kernel, stride 1, padding 1
conv_layer = nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding)

In [ ]:
conv_layer_out = conv_layer(conv_input)
print(f'conv layer output shape: {conv_layer_out.shape}')

conv layer output shape: torch.Size([3, 3, 5, 5])


## Maxpooling layer

- PyTorch provides convolution layer called ```nn.MaxPool2d```, which we looked at Assignment 4.
    - There are different kinds of pooling, but we only cover ```nn.MaxPool2d```.
- It takes ```kernel_size```, ```stride```, and ```padding``` as basic arguments. (There are more, but we do not consider here.)
- ```kernel_size``` can be integer or a tuple.
    - If an integer is given, kernel is squared shape.
    - If a tuple is given, kernel is of the given shape.
    - Square kernel is common.
- Input and output shape is as follows:
    - Input: (# data, in_channel, in_height, in_width)
    - Input: (# data, out_channel, out_height, out_width)
- Refer to official document of [nn.MaxPool2d](https://pytorch.org/docs/master/generated/torch.nn.MaxPool2d.html#torch.nn.MaxPool2d) for more information.

In [ ]:
maxpool_input = torch.FloatTensor([[1] * 5, [2] * 5, [3] * 5, [4] * 5, [5] * 5]).view(1, 1, 5, 5)
maxpool_layer = nn.MaxPool2d(kernel_size=3, stride=1, padding=0)
maxpool_out = maxpool_layer(maxpool_input)

print(f'maxpool layer input: \n{maxpool_input[0, 0]}')
print(f'maxpool layer input shape: {maxpool_input.shape}')

print(f'maxpool layer output: \n{maxpool_out[0, 0]}')
print(f'maxpool layer output shape: {maxpool_out.shape}')

maxpool layer input: 
tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.]])
maxpool layer input shape: torch.Size([1, 1, 5, 5])
maxpool layer output: 
tensor([[3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.]])
maxpool layer output shape: torch.Size([1, 1, 3, 3])


## Activation Functions

- PyTorch provides various activation functions, including sigmoid, tanh, and ReLU.
- Activation function is also a module, so you should follow same steps: build and use like a function.
- Here, we will cover sigmoid, tanh, and ReLU.
- Refer to official document of [Non-linear Activations](https://pytorch.org/docs/master/nn.html#non-linear-activations-weighted-sum-nonlinearity) for more functions.

In [ ]:
sigmoid = nn.Sigmoid()
tanh = nn.Tanh()
relu = nn.ReLU()

x = torch.randn(3, 3)
sigmoid_out = sigmoid(x)
tanh_out = tanh(x)
relu_out = relu(x)

print(f'Input x:\n {x}')
print(f'Sigmoid:\n {sigmoid_out}')
print(f'Tanh:\n {tanh_out}')
print(f'ReLU:\n {relu_out}')

Input x:
 tensor([[-0.8236, -1.6671, -0.5744],
        [-0.0760, -0.1382, -0.5599],
        [-0.2259, -0.6567,  0.0340]])
Sigmoid:
 tensor([[0.3050, 0.1588, 0.3602],
        [0.4810, 0.4655, 0.3636],
        [0.4438, 0.3415, 0.5085]])
Tanh:
 tensor([[-0.6770, -0.9312, -0.5186],
        [-0.0758, -0.1373, -0.5079],
        [-0.2222, -0.5762,  0.0340]])
ReLU:
 tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0340]])
