In [1]:
import numpy as np
import tensorflow as tf
from pprint import pprint

In [2]:
x = tf.constant(5.0)

def f(x, power=3):
    return tf.pow(x, power)

with tf.GradientTape() as tape:
    tape.watch(x)
    y = f(x)

# pprint(tape.gradient(y, x).numpy()) # -> 75.0
pprint(tape.gradient(target=y, sources=[x]))

[<tf.Tensor: shape=(), dtype=float32, numpy=75.0>]


In [3]:
a = tf.Variable([4], dtype=tf.float32)
b = tf.Variable([5], dtype=tf.float32)
def f(a, b, power=3, d=3):
    return tf.pow(a, power) + d * b
with tf.GradientTape(watch_accessed_variables=True) as tape:
    c = f(a, b)
pprint(tape.gradient(target=c, sources=[a, b]))



[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([48.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>]


In [4]:
d = tf.constant(3, dtype=tf.float32)
with tf.GradientTape() as tape:
    tape.watch(d)
    c = f(a, b, d=d)
pprint(tape.gradient(target=c, sources=[d]))

[<tf.Tensor: shape=(), dtype=float32, numpy=5.0>]


In [5]:
with tf.GradientTape(persistent=True) as tape:
    c = f(a, b)
pprint(tape.gradient(c, [a]))
pprint(tape.gradient(c, [b]))

[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([48.], dtype=float32)>]
[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>]


In [6]:
# RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.
with tf.GradientTape() as tape:
    c = f(a, b)
pprint(tape.gradient(c, [a]))
pprint(tape.gradient(c, [b]))

[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([48.], dtype=float32)>]


RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.