In [1]:
import numpy as np
import tensorflow as tf
from pprint import pprint

In [2]:
# ground truth
true_weights = tf.constant(list(range(5)), dtype=tf.float32)[:, tf.newaxis]
true_weights

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]], dtype=float32)>

In [3]:
# some random training data
x = tf.constant(tf.random.uniform((32, 5)), dtype=tf.float32)
y = tf.constant(x @ true_weights, dtype=tf.float32)
pprint(x)
pprint(y)

<tf.Tensor: shape=(32, 5), dtype=float32, numpy=
array([[0.7002722 , 0.24240613, 0.36603093, 0.7869246 , 0.32483244],
       [0.13621354, 0.92264414, 0.04672873, 0.8722913 , 0.83894837],
       [0.6610607 , 0.30045998, 0.7715732 , 0.8334985 , 0.5688288 ],
       [0.28000474, 0.12908816, 0.714069  , 0.5418378 , 0.79063475],
       [0.6224332 , 0.6061647 , 0.27062547, 0.12274373, 0.5862247 ],
       [0.6680366 , 0.7745929 , 0.46733868, 0.45637977, 0.6191393 ],
       [0.3426783 , 0.05436754, 0.716414  , 0.7566786 , 0.23408353],
       [0.03379881, 0.39573884, 0.77124786, 0.01030278, 0.13139725],
       [0.9226649 , 0.63663065, 0.46112335, 0.35627687, 0.8740721 ],
       [0.87078273, 0.21959078, 0.7450887 , 0.343997  , 0.70119035],
       [0.79227734, 0.9510634 , 0.04753792, 0.8286134 , 0.7942163 ],
       [0.39978492, 0.17558384, 0.24328423, 0.49246502, 0.456977  ],
       [0.665903  , 0.36734152, 0.13458002, 0.69761145, 0.26371193],
       [0.31050205, 0.16827965, 0.8386116 , 0.38141954

In [4]:
# z = tf.linalg.matmul(x, true_weights)
z = x @ true_weights
pprint(z)

<tf.Tensor: shape=(32, 1), dtype=float32, numpy=
array([[4.6345716],
       [6.988769 ],
       [6.619417 ],
       [6.3452787],
       [3.8605456],
       [5.554967 ],
       [4.6935654],
       [2.494732 ],
       [6.1239963],
       [5.5465207],
       [6.7088447],
       [3.9674554],
       [3.7841837],
       [3.1526008],
       [3.3264346],
       [6.556922 ],
       [5.2095866],
       [2.1681924],
       [6.241415 ],
       [4.9072995],
       [6.6946535],
       [6.1054316],
       [3.8939857],
       [3.2359385],
       [6.3458943],
       [6.533107 ],
       [5.287026 ],
       [7.1055894],
       [5.0975657],
       [2.494865 ],
       [5.9388423],
       [3.8864763]], dtype=float32)>


In [5]:
# model parameters
weights = tf.Variable(tf.random.uniform((5, 1)), dtype=tf.float32)
pprint(weights)

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[0.6779481 ],
       [0.6463821 ],
       [0.5372791 ],
       [0.25257266],
       [0.03718925]], dtype=float32)>


In [6]:
# calculate true weights using gradient of loss function
for iteration in range(1001):
    with tf.GradientTape() as tape:
        y_hat = tf.linalg.matmul(x, weights)
        loss = tf.reduce_mean(tf.square(y - y_hat))
    if not (iteration % 100):
        print('mean squared loss at iteration {:4d} is {:5.4f}'.format
              (iteration, loss))
    gradients = tape.gradient(loss, weights)
    weights.assign_add(-0.1 * gradients)
pprint(weights)

mean squared loss at iteration    0 is 17.4714
mean squared loss at iteration  100 is 0.0834
mean squared loss at iteration  200 is 0.0121
mean squared loss at iteration  300 is 0.0019
mean squared loss at iteration  400 is 0.0003
mean squared loss at iteration  500 is 0.0001
mean squared loss at iteration  600 is 0.0000
mean squared loss at iteration  700 is 0.0000
mean squared loss at iteration  800 is 0.0000
mean squared loss at iteration  900 is 0.0000
mean squared loss at iteration 1000 is 0.0000
<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[1.1309592e-04],
       [1.0001228e+00],
       [2.0001121e+00],
       [3.0000324e+00],
       [3.9996564e+00]], dtype=float32)>
