In [1]:
import numpy as np
import tensorflow as tf
from pprint import pprint

In [2]:
# ground truth
true_weights = tf.constant(list(range(5)), dtype=tf.float32)[:, tf.newaxis]
true_weights

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]], dtype=float32)>

In [3]:
# some random training data
x = tf.constant(tf.random.uniform((32, 5)), dtype=tf.float32)
y = tf.constant(x @ true_weights, dtype=tf.float32)
pprint(x)
pprint(y)

<tf.Tensor: shape=(32, 5), dtype=float32, numpy=
array([[0.50827897, 0.68472016, 0.663056  , 0.35499907, 0.9935324 ],
       [0.4008205 , 0.21873057, 0.63302207, 0.5512996 , 0.43582392],
       [0.26583052, 0.38076222, 0.07814848, 0.88594973, 0.6069381 ],
       [0.9746609 , 0.47897816, 0.2755072 , 0.6729342 , 0.7206811 ],
       [0.22948503, 0.41642725, 0.15160847, 0.6733655 , 0.5963161 ],
       [0.10002267, 0.33886755, 0.7351037 , 0.2793635 , 0.9117718 ],
       [0.6929182 , 0.21131074, 0.5820744 , 0.7700647 , 0.2142787 ],
       [0.21243012, 0.6621958 , 0.01394904, 0.7591262 , 0.21653199],
       [0.54789996, 0.13434839, 0.20061994, 0.66866565, 0.08818734],
       [0.6378305 , 0.22295201, 0.17221606, 0.6294701 , 0.32779562],
       [0.92749953, 0.44916463, 0.99735594, 0.3138337 , 0.7281059 ],
       [0.67789495, 0.42812932, 0.04376686, 0.8314651 , 0.01854885],
       [0.15297997, 0.92780066, 0.51139987, 0.9148418 , 0.27252507],
       [0.83436775, 0.25798488, 0.30214775, 0.9247707 

In [4]:
# z = tf.linalg.matmul(x, true_weights)
z = x @ true_weights
pprint(z)

<tf.Tensor: shape=(32, 1), dtype=float32, numpy=
array([[7.049959 ],
       [4.881969 ],
       [5.622661 ],
       [5.9315195],
       [5.125005 ],
       [6.2942524],
       [4.5427685],
       [3.8336005],
       [2.8943346],
       [3.7669768],
       [6.297801 ],
       [3.0842538],
       [5.785226 ],
       [4.056805 ],
       [6.269926 ],
       [5.715556 ],
       [5.136047 ],
       [5.9674897],
       [4.3431964],
       [4.801418 ],
       [4.705911 ],
       [2.1543977],
       [4.5709877],
       [7.037346 ],
       [5.339777 ],
       [5.0256515],
       [3.8558435],
       [7.4641705],
       [6.9123945],
       [7.8322225],
       [5.9227138],
       [2.3032446]], dtype=float32)>


In [5]:
# model parameters
weights = tf.Variable(tf.random.uniform((5, 1)), dtype=tf.float32)
pprint(weights)

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[0.88392293],
       [0.8370509 ],
       [0.6732271 ],
       [0.6723341 ],
       [0.8484428 ]], dtype=float32)>


In [7]:
# calculate true weights using gradient of loss function
for iteration in range(1001):
    with tf.GradientTape() as tape:
        y_hat = tf.linalg.matmul(x, weights)
        loss = tf.reduce_mean(tf.square(y - y_hat))
    if not (iteration % 100):
        print('mean squared loss at iteration {:4d} is {:5.4f}'.format
              (iteration, loss))
    gradients = tape.gradient(loss, weights)
    weights.assign_add(-0.5 * gradients)
pprint(weights)

mean squared loss at iteration    0 is 0.0000
mean squared loss at iteration  100 is 0.0000
mean squared loss at iteration  200 is 0.0000
mean squared loss at iteration  300 is 0.0000


mean squared loss at iteration  400 is 0.0000
mean squared loss at iteration  500 is 0.0000
mean squared loss at iteration  600 is 0.0000


mean squared loss at iteration  700 is 0.0000
mean squared loss at iteration  800 is 0.0000
mean squared loss at iteration  900 is 0.0000
mean squared loss at iteration 1000 is 0.0000
<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[2.3329414e-07],
       [1.0000010e+00],
       [2.0000005e+00],
       [2.9999995e+00],
       [3.9999988e+00]], dtype=float32)>
