In [14]:
import numpy as np
import tensorflow as tf
from pprint import pprint

In [15]:
x = tf.random.uniform((3, 2))
e = tf.random.uniform((3, 2), dtype=x.dtype)
pprint(x)
pprint(e)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6887747 , 0.5543525 ],
       [0.31465697, 0.34848368],
       [0.1494317 , 0.42190182]], dtype=float32)>
<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7059096 , 0.90384674],
       [0.7696272 , 0.59107554],
       [0.00255585, 0.8723327 ]], dtype=float32)>


In [16]:

pprint(tf.math.reduce_all(x.__add__(e) == tf.add(x, e)))
tf.add(x, e)

<tf.Tensor: shape=(), dtype=bool, numpy=True>


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.3946843 , 1.4581993 ],
       [1.0842842 , 0.9395592 ],
       [0.15198755, 1.2942345 ]], dtype=float32)>

In [17]:
x_numpy = x.numpy()
print(type(x_numpy))
pprint(x_numpy)
x_numpy

<class 'numpy.ndarray'>
array([[0.6887747 , 0.5543525 ],
       [0.31465697, 0.34848368],
       [0.1494317 , 0.42190182]], dtype=float32)


array([[0.6887747 , 0.5543525 ],
       [0.31465697, 0.34848368],
       [0.1494317 , 0.42190182]], dtype=float32)

In [18]:
with tf.device('/cpu:0'):
    x_cpu = tf.identity(x)
with tf.device('/gpu:0'):
    x_gpu = tf.identity(x)
print(x_cpu.device)
print(x_gpu.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [19]:
e = tf.random.uniform((3, 2), dtype=x.dtype)
pprint(tf.math.reduce_all(x.__add__(e) == tf.add(x, e)))
tf.add(x, e)

<tf.Tensor: shape=(), dtype=bool, numpy=True>


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.5547906 , 1.0875286 ],
       [0.94117725, 0.8026298 ],
       [0.99945843, 1.2125037 ]], dtype=float32)>

In [20]:
pprint(tf.math.reduce_all(x.__mul__(e) == tf.multiply(x, e)))
x.__mul__(e) == tf.multiply(x, e)

<tf.Tensor: shape=(), dtype=bool, numpy=True>


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [21]:
pprint(tf.math.reduce_all(x.__matmul__(tf.transpose(e)) == tf.linalg.matmul(x, e, transpose_b=True)))
x.__matmul__(tf.transpose(e)) == tf.linalg.matmul(x, e, transpose_b=True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>


<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [24]:
matrix = tf.constant(np.array([[1, 2], [3, 4]]), dtype=tf.float32)
pprint(matrix[0, 1])
pprint(matrix[1, :2])
pprint(matrix[tf.newaxis, 1, :2])

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>
<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[3., 4.]], dtype=float32)>
