In [1]:
import numpy as np
import tensorflow as tf
from pprint import pprint

In [2]:
x = tf.random.uniform((3, 2))

In [3]:
v = tf.Variable(x)
pprint(v)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0.3483125 , 0.2046386 ],
       [0.7643287 , 0.69860435],
       [0.4458078 , 0.6048821 ]], dtype=float32)>


In [4]:
pprint(tf.square(x))
pprint(tf.square(v))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.1213216 , 0.04187696],
       [0.5841984 , 0.48804802],
       [0.19874461, 0.36588237]], dtype=float32)>
<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.1213216 , 0.04187696],
       [0.5841984 , 0.48804802],
       [0.19874461, 0.36588237]], dtype=float32)>


In [15]:
v.assign(tf.square(v))
pprint(v)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[1.2789769e-13, 0.0000000e+00],
       [8.8257352e-03, 5.8383652e-04],
       [3.7756820e-10, 6.3601415e-06]], dtype=float32)>


In [16]:
v.assign_sub(1 * tf.ones_like(v, dtype=v.dtype))
pprint(v)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-1.       , -1.       ],
       [-0.9911743, -0.9994162],
       [-1.       , -0.9999936]], dtype=float32)>
