In [31]:
# Code from https://www.youtube.com/watch?v=9YbTeY-IP4c&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=19
import pandas as pd

In [32]:
# !wget https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv

In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv')

In [34]:
type(df)

pandas.core.frame.DataFrame

In [35]:
df.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>2013-02-08</td>
      <td>27.920</td>
      <td>28.325</td>
      <td>27.920</td>
      <td>28.185</td>
      <td>7146296</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1</td>
      <td>2013-02-11</td>
      <td>28.260</td>
      <td>28.260</td>
      <td>27.930</td>
      <td>28.070</td>
      <td>5457354</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>2</td>
      <td>2013-02-12</td>
      <td>28.000</td>
      <td>28.275</td>
      <td>27.975</td>
      <td>28.130</td>
      <td>8665592</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>3</td>
      <td>2013-02-13</td>
      <td>28.230</td>
      <td>28.230</td>
      <td>27.750</td>
      <td>27.915</td>
      <td>7022056</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>4</td>
      <td>2013-02-14</td>
      <td>27.765</td>
      <td>27.905</td>
      <td>27.675</td>
      <td>27.775</td>
      <td>8899188</td>
      <td>SBUX</td>
    </tr>
  </tbody>
</table>
</div>

In [36]:
df.head(10)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>2013-02-08</td>
      <td>27.920</td>
      <td>28.325</td>
      <td>27.920</td>
      <td>28.185</td>
      <td>7146296</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1</td>
      <td>2013-02-11</td>
      <td>28.260</td>
      <td>28.260</td>
      <td>27.930</td>
      <td>28.070</td>
      <td>5457354</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>2</td>
      <td>2013-02-12</td>
      <td>28.000</td>
      <td>28.275</td>
      <td>27.975</td>
      <td>28.130</td>
      <td>8665592</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>3</td>
      <td>2013-02-13</td>
      <td>28.230</td>
      <td>28.230</td>
      <td>27.750</td>
      <td>27.915</td>
      <td>7022056</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>4</td>
      <td>2013-02-14</td>
      <td>27.765</td>
      <td>27.905</td>
      <td>27.675</td>
      <td>27.775</td>
      <td>8899188</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>5</td>
      <td>2013-02-15</td>
      <td>27.805</td>
      <td>27.850</td>
      <td>27.085</td>
      <td>27.170</td>
      <td>18195730</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>6</td>
      <td>2013-02-19</td>
      <td>27.180</td>
      <td>27.305</td>
      <td>27.010</td>
      <td>27.225</td>
      <td>11760912</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>7</td>
      <td>2013-02-20</td>
      <td>27.300</td>
      <td>27.420</td>
      <td>26.590</td>
      <td>26.655</td>
      <td>12472506</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>8</td>
      <td>2013-02-21</td>
      <td>26.535</td>
      <td>26.820</td>
      <td>26.260</td>
      <td>26.675</td>
      <td>13896450</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>9</td>
      <td>2013-02-22</td>
      <td>26.850</td>
      <td>27.105</td>
      <td>26.640</td>
      <td>27.085</td>
      <td>11487316</td>
      <td>SBUX</td>
    </tr>
  </tbody>
</table>
</div>

In [37]:
df.size

8813

In [38]:
df.tail()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1254</td>
      <td>2018-02-01</td>
      <td>56.280</td>
      <td>56.42</td>
      <td>55.89</td>
      <td>56.00</td>
      <td>14690146</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1255</td>
      <td>2018-02-02</td>
      <td>55.900</td>
      <td>56.32</td>
      <td>55.70</td>
      <td>55.77</td>
      <td>15358909</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1256</td>
      <td>2018-02-05</td>
      <td>55.530</td>
      <td>56.26</td>
      <td>54.57</td>
      <td>54.69</td>
      <td>16059955</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1257</td>
      <td>2018-02-06</td>
      <td>53.685</td>
      <td>56.06</td>
      <td>53.56</td>
      <td>55.61</td>
      <td>17415065</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1258</td>
      <td>2018-02-07</td>
      <td>55.080</td>
      <td>55.43</td>
      <td>54.44</td>
      <td>54.46</td>
      <td>13927022</td>
      <td>SBUX</td>
    </tr>
  </tbody>
</table>
</div>

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 7 columns):
date      1259 non-null object
open      1259 non-null float64
high      1259 non-null float64
low       1259 non-null float64
close     1259 non-null float64
volume    1259 non-null int64
Name      1259 non-null object
dtypes: float64(4), int64(1), object(2)
memory usage: 69.0+ KB


In [40]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [41]:
df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'name']

In [42]:
df.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>2013-02-08</td>
      <td>27.920</td>
      <td>28.325</td>
      <td>27.920</td>
      <td>28.185</td>
      <td>7146296</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1</td>
      <td>2013-02-11</td>
      <td>28.260</td>
      <td>28.260</td>
      <td>27.930</td>
      <td>28.070</td>
      <td>5457354</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>2</td>
      <td>2013-02-12</td>
      <td>28.000</td>
      <td>28.275</td>
      <td>27.975</td>
      <td>28.130</td>
      <td>8665592</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>3</td>
      <td>2013-02-13</td>
      <td>28.230</td>
      <td>28.230</td>
      <td>27.750</td>
      <td>27.915</td>
      <td>7022056</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>4</td>
      <td>2013-02-14</td>
      <td>27.765</td>
      <td>27.905</td>
      <td>27.675</td>
      <td>27.775</td>
      <td>8899188</td>
      <td>SBUX</td>
    </tr>
  </tbody>
</table>
</div>

In [43]:
df['open']

0       27.920
1       28.260
2       28.000
3       28.230
4       27.765
         ...  
1254    56.280
1255    55.900
1256    55.530
1257    53.685
1258    55.080
Name: open, Length: 1259, dtype: float64

In [44]:
type(df['open'])

pandas.core.series.Series

In [45]:
df[['open', 'close']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>close</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>27.920</td>
      <td>28.185</td>
    </tr>
    <tr>
      <td>1</td>
      <td>28.260</td>
      <td>28.070</td>
    </tr>
    <tr>
      <td>2</td>
      <td>28.000</td>
      <td>28.130</td>
    </tr>
    <tr>
      <td>3</td>
      <td>28.230</td>
      <td>27.915</td>
    </tr>
    <tr>
      <td>4</td>
      <td>27.765</td>
      <td>27.775</td>
    </tr>
    <tr>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <td>1254</td>
      <td>56.280</td>
      <td>56.000</td>
    </tr>
    <tr>
      <td>1255</td>
      <td>55.900</td>
      <td>55.770</td>
    </tr>
    <tr>
      <td>1256</td>
      <td>55.530</td>
      <td>54.690</td>
    </tr>
    <tr>
      <td>1257</td>
      <td>53.685</td>
      <td>55.610</td>
    </tr>
    <tr>
      <td>1258</td>
      <td>55.080</td>
      <td>54.460</td>
    </tr>
  </tbody>
</table>
<p>1259 rows × 2 columns</p>
</div>

In [46]:
type(df[['open', 'close']])

pandas.core.frame.DataFrame

In [47]:
# select row by integer index
df.iloc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
name            SBUX
Name: 0, dtype: object

In [48]:
# select row by index label
df.loc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
name            SBUX
Name: 0, dtype: object

In [49]:
# set index column
df2 = pd.read_csv('https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv', index_col='date')

In [50]:
df2.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>Name</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>2013-02-08</td>
      <td>27.920</td>
      <td>28.325</td>
      <td>27.920</td>
      <td>28.185</td>
      <td>7146296</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>2013-02-11</td>
      <td>28.260</td>
      <td>28.260</td>
      <td>27.930</td>
      <td>28.070</td>
      <td>5457354</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>2013-02-12</td>
      <td>28.000</td>
      <td>28.275</td>
      <td>27.975</td>
      <td>28.130</td>
      <td>8665592</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>2013-02-13</td>
      <td>28.230</td>
      <td>28.230</td>
      <td>27.750</td>
      <td>27.915</td>
      <td>7022056</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>2013-02-14</td>
      <td>27.765</td>
      <td>27.905</td>
      <td>27.675</td>
      <td>27.775</td>
      <td>8899188</td>
      <td>SBUX</td>
    </tr>
  </tbody>
</table>
</div>

In [51]:
df2.loc['2013-02-11']

open        28.26
high        28.26
low         27.93
close       28.07
volume    5457354
Name         SBUX
Name: 2013-02-11, dtype: object

In [52]:
# select rows
df[df['open'] > 64]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1087</td>
      <td>2017-06-05</td>
      <td>64.85</td>
      <td>64.870</td>
      <td>64.18</td>
      <td>64.27</td>
      <td>6809284</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1088</td>
      <td>2017-06-06</td>
      <td>64.22</td>
      <td>64.350</td>
      <td>64.05</td>
      <td>64.16</td>
      <td>5448439</td>
      <td>SBUX</td>
    </tr>
    <tr>
      <td>1089</td>
      <td>2017-06-07</td>
      <td>64.13</td>
      <td>64.295</td>
      <td>63.34</td>
      <td>63.50</td>
      <td>8364994</td>
      <td>SBUX</td>
    </tr>
  </tbody>
</table>
</div>

In [53]:
df[df['name'] != 'SBUX']

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</div>

In [54]:
df['name'] != 'SBUX'

0       False
1       False
2       False
3       False
4       False
        ...  
1254    False
1255    False
1256    False
1257    False
1258    False
Name: name, Length: 1259, dtype: bool

In [55]:
type(df['name'] != 'SBUX')

pandas.core.series.Series

In [56]:
import numpy as np
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
A[A % 2 == 0]

array([0, 2, 4, 6, 8])

In [58]:
A % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [59]:
df.values

In [60]:
A = df[['open', 'close']].values
A

In [61]:
type(A)

numpy.ndarray

In [62]:
small_df = df[['open', 'close']]
small_df.to_csv('output.csv')

PermissionError: [Errno 13] Permission denied: 'output.csv'

In [63]:
# save without index
small_df.to_csv('output.csv', index=False)

PermissionError: [Errno 13] Permission denied: 'output.csv'