In [51]:
# Code from https://www.youtube.com/watch?v=9YbTeY-IP4c&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=19
import pandas as pd

In [52]:
# !wget https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv

In [53]:
df = pd.read_csv('https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv')

In [54]:
type(df)

pandas.core.frame.DataFrame

In [55]:
df.head()

date    open    high     low   close   volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [56]:
df.head(10)

date    open    high     low   close    volume  Name
0  2013-02-08  27.920  28.325  27.920  28.185   7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070   5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130   8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915   7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775   8899188  SBUX
5  2013-02-15  27.805  27.850  27.085  27.170  18195730  SBUX
6  2013-02-19  27.180  27.305  27.010  27.225  11760912  SBUX
7  2013-02-20  27.300  27.420  26.590  26.655  12472506  SBUX
8  2013-02-21  26.535  26.820  26.260  26.675  13896450  SBUX
9  2013-02-22  26.850  27.105  26.640  27.085  11487316  SBUX

In [57]:
df.size

8813

In [58]:
df.tail()

date    open   high    low  close    volume  Name
1254  2018-02-01  56.280  56.42  55.89  56.00  14690146  SBUX
1255  2018-02-02  55.900  56.32  55.70  55.77  15358909  SBUX
1256  2018-02-05  55.530  56.26  54.57  54.69  16059955  SBUX
1257  2018-02-06  53.685  56.06  53.56  55.61  17415065  SBUX
1258  2018-02-07  55.080  55.43  54.44  54.46  13927022  SBUX

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 7 columns):
date      1259 non-null object
open      1259 non-null float64
high      1259 non-null float64
low       1259 non-null float64
close     1259 non-null float64
volume    1259 non-null int64
Name      1259 non-null object
dtypes: float64(4), int64(1), object(2)
memory usage: 69.0+ KB


In [60]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'Name'], dtype='object')

In [61]:
df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'name']

In [62]:
df.head()

date    open    high     low   close   volume  name
0  2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
1  2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2  2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
3  2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
4  2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [63]:
df['open']

0       27.920
1       28.260
2       28.000
3       28.230
4       27.765
         ...  
1254    56.280
1255    55.900
1256    55.530
1257    53.685
1258    55.080
Name: open, Length: 1259, dtype: float64

In [64]:
type(df['open'])

pandas.core.series.Series

In [67]:
df[['open', 'close']]

open   close
0     27.920  28.185
1     28.260  28.070
2     28.000  28.130
3     28.230  27.915
4     27.765  27.775
...      ...     ...
1254  56.280  56.000
1255  55.900  55.770
1256  55.530  54.690
1257  53.685  55.610
1258  55.080  54.460

[1259 rows x 2 columns]

In [70]:
# Reverse
# df.iloc[::-1]
df_rev = df.reindex(index=df.index[::-1])
df_rev

date    open    high     low   close    volume  name
1258  2018-02-07  55.080  55.430  54.440  54.460  13927022  SBUX
1257  2018-02-06  53.685  56.060  53.560  55.610  17415065  SBUX
1256  2018-02-05  55.530  56.260  54.570  54.690  16059955  SBUX
1255  2018-02-02  55.900  56.320  55.700  55.770  15358909  SBUX
1254  2018-02-01  56.280  56.420  55.890  56.000  14690146  SBUX
...          ...     ...     ...     ...     ...       ...   ...
4     2013-02-14  27.765  27.905  27.675  27.775   8899188  SBUX
3     2013-02-13  28.230  28.230  27.750  27.915   7022056  SBUX
2     2013-02-12  28.000  28.275  27.975  28.130   8665592  SBUX
1     2013-02-11  28.260  28.260  27.930  28.070   5457354  SBUX
0     2013-02-08  27.920  28.325  27.920  28.185   7146296  SBUX

[1259 rows x 7 columns]

In [71]:
df_rev.reset_index(inplace=True, drop=True)
df_rev

date    open    high     low   close    volume  name
0     2018-02-07  55.080  55.430  54.440  54.460  13927022  SBUX
1     2018-02-06  53.685  56.060  53.560  55.610  17415065  SBUX
2     2018-02-05  55.530  56.260  54.570  54.690  16059955  SBUX
3     2018-02-02  55.900  56.320  55.700  55.770  15358909  SBUX
4     2018-02-01  56.280  56.420  55.890  56.000  14690146  SBUX
...          ...     ...     ...     ...     ...       ...   ...
1254  2013-02-14  27.765  27.905  27.675  27.775   8899188  SBUX
1255  2013-02-13  28.230  28.230  27.750  27.915   7022056  SBUX
1256  2013-02-12  28.000  28.275  27.975  28.130   8665592  SBUX
1257  2013-02-11  28.260  28.260  27.930  28.070   5457354  SBUX
1258  2013-02-08  27.920  28.325  27.920  28.185   7146296  SBUX

[1259 rows x 7 columns]

In [27]:
type(df[['open', 'close']])

pandas.core.frame.DataFrame

In [28]:
# select row by integer index
df.iloc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
name            SBUX
Name: 0, dtype: object

In [29]:
# select row by index label
df.loc[0]

date      2013-02-08
open           27.92
high          28.325
low            27.92
close         28.185
volume       7146296
name            SBUX
Name: 0, dtype: object

In [30]:
# set index column
df2 = pd.read_csv('https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/tf2.0/sbux.csv', index_col='date')

In [31]:
df2.head()

open    high     low   close   volume  Name
date                                                     
2013-02-08  27.920  28.325  27.920  28.185  7146296  SBUX
2013-02-11  28.260  28.260  27.930  28.070  5457354  SBUX
2013-02-12  28.000  28.275  27.975  28.130  8665592  SBUX
2013-02-13  28.230  28.230  27.750  27.915  7022056  SBUX
2013-02-14  27.765  27.905  27.675  27.775  8899188  SBUX

In [32]:
df2.loc['2013-02-11']

open        28.26
high        28.26
low         27.93
close       28.07
volume    5457354
Name         SBUX
Name: 2013-02-11, dtype: object

In [33]:
# select rows
df[df['open'] > 64]

date   open    high    low  close   volume  name
1087  2017-06-05  64.85  64.870  64.18  64.27  6809284  SBUX
1088  2017-06-06  64.22  64.350  64.05  64.16  5448439  SBUX
1089  2017-06-07  64.13  64.295  63.34  63.50  8364994  SBUX

In [34]:
df[df['name'] != 'SBUX']

Empty DataFrame
Columns: [date, open, high, low, close, volume, name]
Index: []

In [35]:
df['name'] != 'SBUX'

0       False
1       False
2       False
3       False
4       False
        ...  
1254    False
1255    False
1256    False
1257    False
1258    False
Name: name, Length: 1259, dtype: bool

In [36]:
type(df['name'] != 'SBUX')

pandas.core.series.Series

In [37]:
import numpy as np
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
A[A % 2 == 0]

array([0, 2, 4, 6, 8])

In [39]:
A % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [40]:
df.values

array([['2013-02-08', 27.92, 28.325, ..., 28.185, 7146296, 'SBUX'],
       ['2013-02-11', 28.26, 28.26, ..., 28.07, 5457354, 'SBUX'],
       ['2013-02-12', 28.0, 28.275, ..., 28.13, 8665592, 'SBUX'],
       ...,
       ['2018-02-05', 55.53, 56.26, ..., 54.69, 16059955, 'SBUX'],
       ['2018-02-06', 53.685, 56.06, ..., 55.61, 17415065, 'SBUX'],
       ['2018-02-07', 55.08, 55.43, ..., 54.46, 13927022, 'SBUX']],
      dtype=object)

In [41]:
A = df[['open', 'close']].values
A

array([[27.92 , 28.185],
       [28.26 , 28.07 ],
       [28.   , 28.13 ],
       ...,
       [55.53 , 54.69 ],
       [53.685, 55.61 ],
       [55.08 , 54.46 ]])

In [42]:
type(A)

numpy.ndarray

In [43]:
small_df = df[['open', 'close']]
small_df.to_csv('output.csv')

In [44]:
# save without index
small_df.to_csv('output.csv', index=False)