In [36]:
# Code of https://www.youtube.com/watch?v=C10KmAbCW6A&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=5

In [1]:
import numpy as np
L = [1, 2, 3]
A = np.array([1, 2, 3])

In [2]:
for e in L:
    print(e)

1
2
3


In [3]:
for e in A:
    print(e)

1
2
3


In [4]:
L.append(4)
L

[1, 2, 3, 4]

In [42]:
[L]*2

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [12]:
# No append because the size of an array is fixed
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [13]:
L + [5]

[1, 2, 3, 4, 5]

In [14]:
# Broadcasting
A + np.array([4])

array([5, 6, 7])

In [15]:
# Must be same size
A + np.array([4, 5, 6])

array([5, 7, 9])

In [16]:
A + np.array([4, 5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [17]:
2 * A

array([2, 4, 6])

In [45]:
2 * L
# L * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
L2 = []
for e in L:
    L2.append(e + 3)
L2    

[4, 5, 6, 7]

In [21]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [22]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [23]:
L2 = []
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [24]:
A**2

In [25]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [26]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [27]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [34]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [29]:
A>1

array([False,  True,  True])

In [33]:
B = A
B

array([1, 2, 3])

In [34]:
B[A>1]

array([2, 3])

In [5]:
# --------------------------------------------

In [10]:
A = list(np.zeros(10))
A

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]