In [3]:
# Code from https://www.youtube.com/watch?v=WASuVuALYVE&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=10
import numpy as np

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.random()

0.4745592574089492

In [19]:
np.random.random((2, 3))

array([[0.22883792, 0.26782901, 0.82986846],
       [0.06999869, 0.21946297, 0.40913378]])

In [20]:
np.random.randn(2, 3)

array([[ 0.10385689,  0.16355388, -1.07967176],
       [-0.50395564,  0.50195784, -1.74176061]])

In [21]:
R = np.random.randn(10000)
R.mean()

0.001538681055870867

In [23]:
# the same
np.mean(R)

0.001538681055870867

In [24]:
R.var()

0.9969227104294781

In [25]:
R.std()

0.9984601696760257

In [32]:
R = np.random.randn(10000, 3)
R.shape

(10000, 3)

In [57]:
# mean by rows
R.mean(axis=0)

array([-0.00362573, -0.0135344 , -0.00640737])

In [56]:
# mean by columns
R.mean(axis=1).shape

(10000,)

In [33]:
R[:, 0]

array([-0.39916311,  1.06881377, -0.09666125, ..., -1.04946834,
       -0.80082288,  0.29014081])

In [34]:
R

array([[-0.39916311,  0.98249357,  0.17469242],
       [ 1.06881377, -0.29589713, -0.40628421],
       [-0.09666125,  0.33167598,  0.01326094],
       ...,
       [-1.04946834, -1.34274006,  0.2459908 ],
       [-0.80082288,  1.37759911, -1.26661954],
       [ 0.29014081, -2.17270107,  0.83842842]])

In [40]:
R[:, 0].var()

1.0291422283236185

In [45]:
np.cov(R[:, 0])

array(1.02924515)

In [48]:
np.cov(R).shape

(10000, 10000)

In [49]:
np.cov(R.T)

array([[ 1.02924515, -0.00595119,  0.00976176],
       [-0.00595119,  0.98650149, -0.00329125],
       [ 0.00976176, -0.00329125,  1.00578493]])

In [50]:
np.cov(R, rowvar=False)

array([[ 1.02924515, -0.00595119,  0.00976176],
       [-0.00595119,  0.98650149, -0.00329125],
       [ 0.00976176, -0.00329125,  1.00578493]])

In [52]:
np.random.randint(0, 10, size=(3, 4))

array([[8, 7, 0, 8],
       [4, 2, 6, 9],
       [1, 8, 8, 2]])

In [55]:
np.random.choice(20, size=(5, 6))

array([[13, 19, 11,  0,  0,  1],
       [ 5, 16, 17, 17, 12, 12],
       [11,  4,  2, 11,  3,  8],
       [16,  6,  2,  2, 17,  3],
       [ 1,  7, 13, 18,  6,  0]])