In [47]:
# Code from https://www.youtube.com/watch?v=IXAeTyT3kBM&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=8
import numpy as np

In [48]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [49]:
L[0]

[1, 2]

In [50]:
L[0][1]

2

In [8]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
A[0][1]

2

In [12]:
# the same thing
A[0, 1]

2

In [13]:
# get column
A[:,0]

array([1, 3])

In [16]:
# transpose
A.T

array([[1, 3],
       [2, 4]])

In [17]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [18]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [20]:
B = np.array([[1, 2, 3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# he same as A.dot(B)
A @ B

array([[ 9, 12, 15],
       [19, 26, 33]])

In [29]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [30]:
# determinant
np.linalg.det(A)

-2.0000000000000004

In [31]:
# inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [32]:
# get identity
np.linalg.inv(A) @ A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [33]:
A.trace()

5

In [38]:
# diagonal
A.diagonal()
np.diag(A)

array([1, 4])

In [39]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [40]:
# eigenvalues and eigenvectors
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [41]:
Lam, V = np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [42]:
# False shows a precision issue
V[:, 0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [44]:
# Results are the same
V[:, 0] * Lam[0], A @ V[:, 0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [45]:
# Use allclose for comparison
np.allclose(V[:, 0] * Lam[0], A @ V[:, 0])

True

In [46]:
np.allclose(V @ np.diag(Lam), A @ V)

True