In [4]:
import numpy as np

In [7]:
a = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1,]])
b = np.array([[2, 3, 4, 5], [6, 7, 8, 9], [0, 2, 3, 4,]])
print(a)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2 3 4 5]
 [6 7 8 9]
 [0 2 3 4]]


In [14]:
i = np.random.rand(*a.shape) > 0.8
a[i] = b[i]
print(i)
print(a)
print(b)

[[False False False False]
 [False False  True False]
 [ True False False False]]
[[2 1 1 5]
 [6 7 8 1]
 [0 2 3 1]]
[[2 3 4 5]
 [6 7 8 9]
 [0 2 3 4]]
