In [6]:
# Code from https://www.youtube.com/watch?v=xvzPBnj22kk&list=PLxgDUj5eygKnSd4MYHIuAC7E3VEPm_WLO&index=9
import numpy as np

In [9]:
A = np.array([[1, 1], [1.5, 4]])
b1 = np.array([2200, 5050])
b2 = np.array([[2200], [5050]])

In [10]:
# solve is more accurate than inv + dot
np.linalg.solve(A, b1)

array([1500.,  700.])

In [11]:
# the result depends on b structure
np.linalg.solve(A, b2)

array([[1500.],
       [ 700.]])

In [12]:
np.linalg.inv(A).dot(b1)

array([1500.,  700.])

In [13]:
np.linalg.inv(A).dot(b2)

array([[1500.],
       [ 700.]])